<?php
/**
 * Created by PhpStorm.
 * User: Dola
 * Date: 08/04/2016
 * Time: 21:24
 */

namespace App\Http\Controllers\Api;


use App\User;

class UserApiController extends ApiController
{



    protected function getAll()
    {
        $users = User::all();
        return $users;
    }


    protected function getById($id=null)
    {
        return User::where('id',$id)->first();
    }

    protected function getByUser($username=null)
    {
        return User::where('email',$username)->first();
    }

    protected function getByIds($ids)
    {
        parent::getByIds($ids); // TODO: Change the autogenerated stub
    }

    protected function create()
    {
        parent::create(); // TODO: Change the autogenerated stub
    }


}